# Generated by Django 4.2.13 on 2024-07-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
